### ISSUE TITLE
After Pullrequest it is perhabs time to settle the metadata

### ISSUE THREAD

**Issue by SteffenBrinckmann** [NFDI4Chem/formaTAPIRest#9]
Hey,
perhaps after the pull-request it is time to settle the metadata:
- what author information we require in the .cwl
- what labels we require in the .cwl
- what documentation on instruments, etc we want
- what output glob we want
- partial conversion or full conversion (details than in code)
- talk about input fileformat definition.
- do we want to specify if it is a docker or native (second is faster)
What do you think?

**Comment by SteffenBrinckmann** [comment]
* what to do with measurements that stretch multiple files?

**Comment by sneumann** [comment]
IIRC then CWL allows directories for input/output. For the REST API we'll need to ZIP the stuff. 
CWL should have a ZIP tool, so that'd be our first >1 tool "workflow". Yours, Steffen

**Comment by SteffenBrinckmann** [comment]
Not sure what "IIRC" is, I know "IRC" ;-).
I agree with the rule: "zip for multifile", because one can extract it with everything, incl. python, in memory
